---
title: "DASHBOARD RETUR SPM DCB"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---





```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(readxl)
library(dplyr)
library(plotly)
library(lubridate)
library(tidyr)
library(DT)
library(scales)
```

```{r}
df_in <- read_excel("D:/dashboard/RETUR IN.xlsx", sheet = "ALL RCV") %>%
  mutate(ReceiptDate = as.Date(`Receipt date`),
         Week = floor_date(ReceiptDate, unit = "week", week_start = 1)) %>%
  group_by(Week) %>%
  summarise(ReturMasuk = n(), .groups = "drop")

df_closed <- read_excel("D:/dashboard/RETUR IN.xlsx", sheet = "RCV CLOSED") %>%
  mutate(CloseDate = as.Date(`Close date`),
         Week = floor_date(CloseDate, unit = "week", week_start = 1)) %>%
  group_by(Week) %>%
  summarise(ReturClosed = n(), .groups = "drop")

df_compare <- full_join(df_in, df_closed, by = "Week") %>%
  replace_na(list(ReturMasuk = 0, ReturClosed = 0))

df_long <- df_compare %>%
  pivot_longer(cols = c(ReturMasuk, ReturClosed), names_to = "Tipe", values_to = "Jumlah")


```

# RETUR FROM STORE VS RETUR CLOSED

```{r}
p <- ggplot(df_long, aes(x = Week, y = Jumlah, color = Tipe, fill = Tipe)) +
  geom_col(data = subset(df_long, Tipe == "ReturMasuk"), width = 6, alpha = 0.6) +
  geom_line(data = subset(df_long, Tipe == "ReturClosed"), size = 1) +
  geom_point(data = subset(df_long, Tipe == "ReturClosed"), size = 2) +
  scale_color_manual(values = c("ReturMasuk" = "steelblue", "ReturClosed" = "tomato"),
                     labels = c("ReturMasuk" = "Retur Masuk", "ReturClosed" = "Retur Closed")) +
  scale_fill_manual(values = c("ReturMasuk" = "steelblue", "ReturClosed" = "tomato"),
                    labels = c("ReturMasuk" = "Retur Masuk", "ReturClosed" = "Retur Closed")) +
  labs(title = "",
       x = "Minggu",
       y = "Jumlah Retur",
       color = "",
       fill = "") +
  theme_minimal()
# 3. Interaktif dengan plotly
ggplotly(p)



```

# RETUR CLOSED VS PICK RETUR
```{r}

```



# PICK RETUR VS TAKE RETUR BY SPPLIER
```{r}


```

# SOLUSI GHS
```{r}
GHS <- read_excel("D:/dashboard/GHS.xlsx")
```

```{r}
datatable(GHS,
          caption = "Solusi GHS",
          rownames = TRUE,
          filter = "top",
          options = list(pagelength=100))
```